=== AtlasOfLivingAustralia/bie-api-changes/classification.old.schema.json
{
  "type": "array",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "minItems": 1,
  "uniqueItems": true,
  "items": {
    "type": "object",
    "required": [
      "scientificName",
      "guid",
      "rank",
      "rawRank"
    ],
    "properties": {
      "scientificName": {
        "type": "string",
        "minLength": 1
      },
      "guid": {
        "type": "string",
        "minLength": 1
      },
      "rank": {
        "type": "string",
        "minLength": 1
      },
      "rawRank": {
        "type": "string",
        "minLength": 1
      }
    }
  }
}

=== AtlasOfLivingAustralia/bie-api-changes/classification.old.json
[{"scientificName":"ANIMALIA","guid":"urn:lsid:biodiversity.org.au:afd.taxon:4647863b-760d-4b59-aaa1-502c8cdf8d3c","rank":"kingdom","rawRank":"Kingdom"},{"scientificName":"CHORDATA","guid":"urn:lsid:biodiversity.org.au:afd.taxon:065f1da4-53cd-40b8-a396-80fa5c74dedd","rank":"phylum","rawRank":"Phylum"},{"scientificName":"VERTEBRATA","guid":"urn:lsid:biodiversity.org.au:afd.taxon:5d6076b1-b7c7-487f-9d61-0fea0111cc7e","rank":"subphylum","rawRank":"SubPhylum"},{"scientificName":"GNATHOSTOMATA","guid":"urn:lsid:biodiversity.org.au:afd.taxon:ef5515fd-a0a2-4e16-b61a-0f19f8900f76","rank":"suprageneric","rawRank":"Higher Taxon"},{"scientificName":"MAMMALIA","guid":"urn:lsid:biodiversity.org.au:afd.taxon:e9e7db31-04df-41fb-bd8d-e0b0f3c332d6","rank":"class","rawRank":"Class"},{"scientificName":"MARSUPIALIA","guid":"urn:lsid:biodiversity.org.au:afd.taxon:602afec4-950f-4961-9ad0-74793be8efbf","rank":"subclass","rawRank":"SubClass"},{"scientificName":"DIPROTODONTIA","guid":"urn:lsid:biodiversity.org.au:afd.taxon:6d8079f1-edc9-4aab-aabd-232a32b42471","rank":"order","rawRank":"Order"},{"scientificName":"PHALANGERIDA","guid":"urn:lsid:biodiversity.org.au:afd.taxon:e6733776-808c-4aff-9758-e33223c5029f","rank":"suborder","rawRank":"SubOrder"},{"scientificName":"MACROPODOIDEA","guid":"urn:lsid:biodiversity.org.au:afd.taxon:894143f7-f712-40e1-96f1-418c93755acc","rank":"superfamily","rawRank":"SuperFamily"},{"scientificName":"MACROPODIDAE","guid":"urn:lsid:biodiversity.org.au:afd.taxon:72a1c39f-2435-4c28-a680-714b69ded6f9","rank":"family","rawRank":"Family"},{"scientificName":"MACROPODINAE","guid":"urn:lsid:biodiversity.org.au:afd.taxon:b5affee1-2306-4626-8d36-cfe961547d87","rank":"subfamily","rawRank":"SubFamily"},{"scientificName":"Macropus","guid":"urn:lsid:biodiversity.org.au:afd.taxon:9e6a0bba-de5b-4465-8544-aa8fe3943fab","rank":"genus","rawRank":"Genus"},{"scientificName":"Macropus rufus","guid":"urn:lsid:biodiversity.org.au:afd.taxon:31a9b8b8-4e8f-4343-a15f-2ed24e0bf1ae","rank":"species","rawRank":"Species"}]
