=== AtlasOfLivingAustralia/bie-api-changes/index-fields.new.schema.json
{
  "type": "array",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "minItems": 1,
  "uniqueItems": true,
  "items": {
    "type": "object",
    "required": [
      "dataType",
      "indexed",
      "name",
      "stored"
    ],
    "properties": {
      "dataType": {
        "type": "string",
        "minLength": 1
      },
      "indexed": {
        "type": "boolean"
      },
      "name": {
        "type": "string",
        "minLength": 1
      },
      "numberDistinctValues": {},
      "stored": {
        "type": "boolean"
      }
    }
  }
}

=== AtlasOfLivingAustralia/bie-api-changes/index-fields.old.json
[{"dataType":"long","indexed":true,"name":"_version_","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"acceptedConceptID","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"acceptedConceptName","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"acronym","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"additionalIdentifiers","numberDistinctValues":null,"stored":true},{"dataType":"name_complete","indexed":true,"name":"auto_name_exact","numberDistinctValues":null,"stored":false},{"dataType":"auto_text","indexed":true,"name":"auto_text","numberDistinctValues":null,"stored":false},{"dataType":"auto_text_edge","indexed":true,"name":"auto_text_edge","numberDistinctValues":null,"stored":false},{"dataType":"string","indexed":true,"name":"centroid","numberDistinctValues":null,"stored":true},{"dataType":"text","indexed":true,"name":"commonName","numberDistinctValues":null,"stored":true},{"dataType":"lowercase","indexed":true,"name":"commonNameExact","numberDistinctValues":null,"stored":false},{"dataType":"lowercase","indexed":true,"name":"commonNameSingle","numberDistinctValues":null,"stored":true},{"dataType":"concat_name","indexed":true,"name":"concat_name","numberDistinctValues":null,"stored":false},{"dataType":"string","indexed":true,"name":"conservationStatusACT_s","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"conservationStatusAUS_s","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"conservationStatusNSW_s","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"conservationStatusNT_s","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"conservationStatusQLD_s","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"conservationStatusSA_s","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"conservationStatusTAS_s","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"conservationStatusVIC_s","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"conservationStatusWA_s","numberDistinctValues":null,"stored":true},{"dataType":"text","indexed":true,"name":"content","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"datasetID","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"datasetName","numberDistinctValues":null,"stored":true},{"dataType":"text","indexed":true,"name":"description","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"distribution","numberDistinctValues":null,"stored":true},{"dataType":"text_bie_canonical","indexed":true,"name":"doc_name","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"establishmentMeans","numberDistinctValues":null,"stored":true},{"dataType":"lowercase","indexed":true,"name":"exact_text","numberDistinctValues":null,"stored":false},{"dataType":"string","indexed":true,"name":"format","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"guid","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"id","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"idxtype","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"image","numberDistinctValues":null,"stored":true},{"dataType":"boolean","indexed":true,"name":"imageAvailable","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"language","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"license","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"linkIdentifier","numberDistinctValues":null,"stored":true},{"dataType":"boolean","indexed":true,"name":"locatedInHubCountry","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"name","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"nameComplete","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"nameFormatted","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"nameID","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":false,"name":"namePublishedIn","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":false,"name":"namePublishedInID","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":false,"name":"namePublishedInYear","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"nomenclaturalStatus","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"parentGuid","numberDistinctValues":null,"stored":true},{"dataType":"int","indexed":false,"name":"priority","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rank","numberDistinctValues":null,"stored":true},{"dataType":"int","indexed":true,"name":"rankID","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rights","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_anamorph","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_class","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_cohort","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_division","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_division_zoology","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_family","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_form","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_genus","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_genus_group","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_higher_taxon","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_infraclass","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_infrafamily","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_infraorder","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_kingdom","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_order","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_phylum","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_section","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_section_zoology","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_species","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_species_group","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_subclass","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_subdivision_zoology","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_subfamily","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_subgenus","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_subkingdom","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_suborder","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_subphylum","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_subsection_zoology","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_subspecies","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_subtribe","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_superclass","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_superfamily","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_superorder","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_supertribe","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_tribe","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_unknown","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rk_variety","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rkid_anamorph","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rkid_class","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rkid_cohort","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rkid_division","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rkid_division_zoology","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rkid_family","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rkid_form","numberDistinctValues":null,"stored":true},{"dataType":"string","indexed":true,"name":"rkid_genus","numberDistinctValues":null,"stored":true},{
