=== AtlasOfLivingAustralia/bie-api-changes/species-guid.new.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "type": "object",
  "properties": {
    "taxonConcept": {
      "type": "object",
      "properties": {
        "guid": {
          "type": "string",
          "minLength": 1
        },
        "parentGuid": {
          "type": "string",
          "minLength": 1
        },
        "nameString": {
          "type": "string",
          "minLength": 1
        },
        "nameComplete": {
          "type": "string",
          "minLength": 1
        },
        "nameFormatted": {
          "type": "string",
          "minLength": 1
        },
        "author": {
          "type": "string",
          "minLength": 1
        },
        "rankString": {
          "type": "string",
          "minLength": 1
        },
        "nameAuthority": {
          "type": "string",
          "minLength": 1
        },
        "rankID": {
          "type": "number"
        },
        "namePublishedIn": {},
        "namePublishedInYear": {},
        "namePublishedInID": {},
        "infoSourceURL": {
          "type": "string",
          "minLength": 1
        },
        "datasetURL": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "guid",
        "parentGuid",
        "nameString",
        "nameComplete",
        "nameFormatted",
        "author",
        "rankString",
        "nameAuthority",
        "rankID",
        "infoSourceURL",
        "datasetURL"
      ]
    },
    "taxonName": {
      "type": "array",
      "items": {
        "required": [],
        "properties": {}
      }
    },
    "classification": {
      "type": "object",
      "properties": {
        "class": {
          "type": "string",
          "minLength": 1
        },
        "family": {
          "type": "string",
          "minLength": 1
        },
        "genus": {
          "type": "string",
          "minLength": 1
        },
        "higher_taxon": {
          "type": "string",
          "minLength": 1
        },
        "kingdom": {
          "type": "string",
          "minLength": 1
        },
        "order": {
          "type": "string",
          "minLength": 1
        },
        "phylum": {
          "type": "string",
          "minLength": 1
        },
        "subclass": {
          "type": "string",
          "minLength": 1
        },
        "subfamily": {
          "type": "string",
          "minLength": 1
        },
        "suborder": {
          "type": "string",
          "minLength": 1
        },
        "subphylum": {
          "type": "string",
          "minLength": 1
        },
        "superfamily": {
          "type": "string",
          "minLength": 1
        },
        "classGuid": {
          "type": "string",
          "minLength": 1
        },
        "familyGuid": {
          "type": "string",
          "minLength": 1
        },
        "genusGuid": {
          "type": "string",
          "minLength": 1
        },
        "higher_taxonGuid": {
          "type": "string",
          "minLength": 1
        },
        "kingdomGuid": {
          "type": "string",
          "minLength": 1
        },
        "orderGuid": {
          "type": "string",
          "minLength": 1
        },
        "phylumGuid": {
          "type": "string",
          "minLength": 1
        },
        "subclassGuid": {
          "type": "string",
          "minLength": 1
        },
        "subfamilyGuid": {
          "type": "string",
          "minLength": 1
        },
        "suborderGuid": {
          "type": "string",
          "minLength": 1
        },
        "subphylumGuid": {
          "type": "string",
          "minLength": 1
        },
        "superfamilyGuid": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "class",
        "family",
        "genus",
        "higher_taxon",
        "kingdom",
        "order",
        "phylum",
        "subclass",
        "subfamily",
        "suborder",
        "subphylum",
        "superfamily",
        "classGuid",
        "familyGuid",
        "genusGuid",
        "higher_taxonGuid",
        "kingdomGuid",
        "orderGuid",
        "phylumGuid",
        "subclassGuid",
        "subfamilyGuid",
        "suborderGuid",
        "subphylumGuid",
        "superfamilyGuid"
      ]
    },
    "synonyms": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "required": [
          "nameString",
          "nameComplete",
          "nameFormatted",
          "nameGuid",
          "nameAuthority",
          "infoSourceURL",
          "datasetURL"
        ],
        "properties": {
          "nameString": {
            "type": "string",
            "minLength": 1
          },
          "nameComplete": {
            "type": "string",
            "minLength": 1
          },
          "nameFormatted": {
            "type": "string",
            "minLength": 1
          },
          "nameGuid": {
            "type": "string",
            "minLength": 1
          },
          "namePublishedIn": {},
          "namePublishedInYear": {},
          "namePublishedInID": {},
          "nameAuthority": {
            "type": "string",
            "minLength": 1
          },
          "infoSourceURL": {
            "type": "string",
            "minLength": 1
          },
          "datasetURL": {
            "type": "string",
            "minLength": 1
          }
        }
      }
    },
    "commonNames": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "required": [
          "nameString",
          "status",
          "priority",
          "language",
          "infoSourceName",
          "infoSourceURL",
          "datasetURL"
        ],
        "properties": {
          "nameString": {
            "type": "string",
            "minLength": 1
          },
          "status": {
            "type": "string",
            "minLength": 1
          },
          "priority": {
            "type": "number"
          },
          "language": {
            "type": "string",
            "minLength": 1
          },
          "infoSourceName": {
            "type": "string",
            "minLength": 1
          },
          "infoSourceURL": {
            "type": "string",
            "minLength": 1
          },
          "datasetURL": {
            "type": "string",
            "minLength": 1
          }
        }
      }
    },
    "imageIdentifier": {
      "type": "string",
      "minLength": 1
    },
    "conservationStatuses": {
      "type": "object",
      "properties": {
        "QLD": {
          "type": "object",
          "properties": {
            "dr": {
              "type": "string",
              "minLength": 1
            },
            "status": {
              "type": "string",
              "minLength": 1
            }
          },
          "required": [
            "dr",
            "status"
          ]
        }
      },
      "required": [
        "QLD"
      ]
    },
    "extantStatuses": {
      "type": "array",
      "items": {
        "required": [],
        "properties": {}
      }
    },
    "habitats": {
      "type": "array",
      "items": {
        "required": [],
        "properties": {}
      }
    },
    "categories": {
      "type": "array",
      "items": {
        "required": [],
        "properties": {}
      }
    },
    "simpleProperties": {
      "type": "array",
      "items": {
        "required": [],
        "properties": {}
      }
    },
    "images": {
      "type": "array",
      "items": {
        "required": [],
        "properties": {}
      }
    },
    "identifiers": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "required": [
          "identifier",
          "nameString",
          "status",
          "format",
          "infoSourceName",
          "infoSourceURL",
          "datasetURL"
        ],
        "properties": {
          "identifier": {
            "type": "string",
            "minLength": 1
          },
          "nameString": {
            "type": "string",
            "minLength": 1
          },
          "status": {
            "type": "string",
            "minLength": 1
          },
          "subject": {},
          "format": {
            "type": "string",
            "minLength": 1
          },
          "infoSourceName": {
            "type": "string",
            "minLength": 1
          },
          "infoSourceURL": {
            "type": "string",
            "minLength": 1
          },
          "datasetURL": {
            "type": "string",
            "minLength": 1
          }
        }
      }
    }
  },
  "required": [
    "taxonConcept",
    "taxonName",
    "classification",
    "synonyms",
    "commonNames",
    "imageIdentifier",
    "conservationStatuses",
    "extantStatuses",
    "habitats",
    "categories",
    "simpleProperties",
    "images",
    "identifiers"
  ]
}

=== AtlasOfLivingAustralia/bie-api-changes/species-guid.old.json
{"taxonConcept":{"guid":"urn:lsid:biodiversity.org.au:afd.taxon:31a9b8b8-4e8f-4343-a15f-2ed24e0bf1ae","parentGuid":"urn:lsid:biodiversity.org.au:afd.taxon:9e6a0bba-de5b-4465-8544-aa8fe3943fab","nameString":"Macropus rufus","nameComplete":"Macropus rufus (Desmarest, 1822)","nameFormatted":"<span class=\"scientific-name rank-species\"><span class=\"name\">Macropus rufus<\u002fspan> <span class=\"author\">(Desmarest, 1822)<\u002fspan><\u002fspan>","author":"(Desmarest, 1822)","taxonomicStatus":"accepted","rankString":"species","nameAuthority":"Australian Faunal Directory","rankID":7000,"namePublishedIn":null,"namePublishedInYear":null,"namePublishedInID":null,"infoSourceURL":"http://biodiversity.org.au/afd.taxon/31a9b8b8-4e8f-4343-a15f-2ed24e0bf1ae","datasetURL":"http://collections.ala.org.au/public/show/dr2699","taxonConceptID":"urn:lsid:biodiversity.org.au:afd.taxon:31a9b8b8-4e8f-4343-a15f-2ed24e0bf1ae","scientificNameID":"urn:lsid:biodiversity.org.au:afd.name:292120"},"taxonName":[],"classification":{"class":"MAMMALIA","family":"MACROPODIDAE","genus":"Macropus","higher_taxon":"GNATHOSTOMATA","kingdom":"ANIMALIA","order":"DIPROTODONTIA","phylum":"CHORDATA","subclass":"MARSUPIALIA","subfamily":"MACROPODINAE","suborder":"PHALANGERIDA","subphylum":"VERTEBRATA","superfamily":"MACROPODOIDEA","classGuid":"urn:lsid:biodiversity.org.au:afd.taxon:e9e7db31-04df-41fb-bd8d-e0b0f3c332d6","familyGuid":"urn:lsid:biodiversity.org.au:afd.taxon:72e28d9f-375f-4728-bd99-d2b2a5d1f1f2","genusGuid":"urn:lsid:biodiversity.org.au:afd.taxon:9e6a0bba-de5b-4465-8544-aa8fe3943fab","higher_taxonGuid":"urn:lsid:biodiversity.org.au:afd.taxon:ef5515fd-a0a2-4e16-b61a-0f19f8900f76","kingdomGuid":"urn:lsid:biodiversity.org.au:afd.taxon:4647863b-760d-4b59-aaa1-502c8cdf8d3c","orderGuid":"urn:lsid:biodiversity.org.au:afd.taxon:bd223248-af12-4ce9-9380-4f9a85be38db","phylumGuid":"urn:lsid:biodiversity.org.au:afd.taxon:065f1da4-53cd-40b8-a396-80fa5c74dedd","subclassGuid":"urn:lsid:biodiversity.org.au:afd.taxon:602afec4-950f-4961-9ad0-74793be8efbf","subfamilyGuid":"urn:lsid:biodiversity.org.au:afd.taxon:b5affee1-2306-4626-8d36-cfe961547d87","suborderGuid":"urn:lsid:biodiversity.org.au:afd.taxon:e6733776-808c-4aff-9758-e33223c5029f","subphylumGuid":"urn:lsid:biodiversity.org.au:afd.taxon:5d6076b1-b7c7-487f-9d61-0fea0111cc7e","superfamilyGuid":"urn:lsid:biodiversity.org.au:afd.taxon:894143f7-f712-40e1-96f1-418c93755acc"},"synonyms":[{"nameString":"Kangurus lanosus","nameComplete":"Kangurus lanosus Gray, 1827","nameFormatted":"<span class=\"scientific-name rank-species\"><span class=\"name\">Kangurus lanosus<\u002fspan> <span class=\"author\">Gray, 1827<\u002fspan><\u002fspan>","nameGuid":"urn:lsid:biodiversity.org.au:afd.name:313512","taxonomicStatus":"synonym","namePublishedIn":null,"namePublishedInYear":null,"namePublishedInID":null,"nameAuthority":"Australian Faunal Directory","infoSourceURL":"http://:biodiversity.org.au/afd.name/313512","datasetURL":"http://collections.ala.org.au/public/show/dr2699"},{"nameString":"Kangurus lanosus","nameComplete":"Kangurus lanosus Gray, 1843","nameFormatted":"<span class=\"scientific-name rank-species\"><span class=\"name\">Kangurus lanosus<\u002fspan> <span class=\"author\">Gray, 1843<\u002fspan><\u002fspan>","nameGuid":"urn:lsid:biodiversity.org.au:afd.name:313513","taxonomicStatus":"synonym","namePublishedIn":null,"namePublishedInYear":null,"namePublishedInID":null,"nameAuthority":"Australian Faunal Directory","infoSourceURL":"http://:biodiversity.org.au/afd.name/313513","datasetURL":"http://collections.ala.org.au/public/show/dr2699"},{"nameString":"Kangurus rufus","nameComplete":"Kangurus rufus Desmarest, 1822","nameFormatted":"<span class=\"scientific-name rank-species\"><span class=\"name\">Kangurus rufus<\u002fspan> <span class=\"author\">Desmarest, 1822<\u002fspan><\u002fspan>","nameGuid":"urn:lsid:biodiversity.org.au:afd.name:291479","taxonomicStatus":"synonym","namePublishedIn":null,"namePublishedInYear":null,"namePublishedInID":null,"nameAuthority":"Australian Faunal Directory","infoSourceURL":"http://:biodiversity.org.au/afd.name/291479","datasetURL":"http://collections.ala.org.au/public/show/dr2699"},{"nameString":"Kangurus laniger","nameComplete":"Kangurus laniger Gaimard, 1823","nameFormatted":"<span class=\"scientific-name rank-species\"><span class=\"name\">Kangurus laniger<\u002fspan> <span class=\"author\">Gaimard, 1823<\u002fspan><\u002fspan>","nameGuid":"urn:lsid:biodiversity.org.au:afd.name:313511","taxonomicStatus":"synonym","namePublishedIn":null,"namePublishedInYear":null,"namePublishedInID":null,"nameAuthority":"Australian Faunal Directory","infoSourceURL":"http://:biodiversity.org.au/afd.name/313511","datasetURL":"http://collections.ala.org.au/public/show/dr2699"},{"nameString":"Kangurus griseolanosus","nameComplete":"Kangurus griseolanosus Quoy & Gaimard, 1825","nameFormatted":"<span class=\"scientific-name rank-species\"><span class=\"name\">Kangurus griseolanosus<\u002fspan> <span class=\"author\">Quoy &amp; Gaimard, 1825<\u002fspan><\u002fspan>","nameGuid":"urn:lsid:biodiversity.org.au:afd.name:412888","taxonomicStatus":"synonym","namePublishedIn":null,"namePublishedInYear":null,"namePublishedInID":null,"nameAuthority":"Australian Faunal Directory","infoSourceURL":"http://:biodiversity.org.au/afd.name/412888","datasetURL":"http://collections.ala.org.au/public/show/dr2699"},{"nameString":"Macropus lanigerus","nameComplete":"Macropus lanigerus Gray, 1825","nameFormatted":"<span class=\"scientific-name rank-species\"><span class=\"name\">Macropus lanigerus<\u002fspan> <span class=\"author\">Gray, 1825<\u002fspan><\u002fspan>","nameGuid":"urn:lsid:biodiversity.org.au:afd.name:346054","taxonomicStatus":"synonym","namePublishedIn":null,"namePublishedInYear":null,"namePublishedInID":null,"nameAuthority":"Australian Faunal Directory","infoSourceURL":"http://:biodiversity.org.au/afd.name/346054","datasetURL":"http://collections.ala.org.au/public/show/dr2699"},{"nameString":"Macropus (Osphranter) pictus","nameComplete":"Macropus (Osphranter) pictus Gould, 1861","nameFormatted":"<span class=\"scientific-name rank-species\"><span class=\"name\">Macropus (Osphranter) pictus<\u002fspan> <span class=\"author\">Gould, 1861<\u002fspan><\u002fspan>","nameGuid":"urn:lsid:biodiversity.org.au:afd.name:453915","taxonomicStatus":"synonym","namePublishedIn":null,"namePublishedInYear":null,"namePublishedInID":null,"nameAuthority":"Australian Faunal Directory","infoSourceURL":"http://:biodiversity.org.au/afd.name/453915","datasetURL":"http://collections.ala.org.au/public/show/dr2699"},{"nameString":"Macropus ruber","nameComplete":"Macropus ruber Crisp, 1862","nameFormatted":"<span class=\"scientific-name rank-species\"><span class=\"name\">Macropus ruber<\u002fspan> <span class=\"author\">Crisp, 1862<\u002fspan><\u002fspan>","nameGuid":"urn:lsid:biodiversity.org.au:afd.name:292119","taxonomicStatus":"synonym","namePublishedIn":null,"namePublishedInYear":null,"namePublishedInID":null,"nameAuthority":"Australian Faunal Directory","infoSourceURL":"http://:biodiversity.org.au/afd.name/292119","datasetURL":"http://collections.ala.org.au/public/show/dr2699"},{"nameString":"Macropus (Boriogale) magnus","nameComplete":"Macropus (Boriogale) magnus Owen, 1874","nameFormatted":"<span class=\"scientific-name rank-species\"><span class=\"name\">Macropus (Boriogale) magnus<\u002fspan> <span class=\"author\">Owen, 1874<\u002fspan><\u002fspan>","nameGuid":"urn:lsid:biodiversity.org.au:afd.name:450922","taxonomicStatus":"synonym","namePublishedIn":null,"namePublishedInYear":null,"namePublishedInID":null,"nameAuthority":"Australian Faunal Directory","infoSourceURL":"http://:biodiversity.org.au/afd.name/450922","datasetURL":"http://collections.ala.org.au/public/show/dr2699"},{"nameString":"Macropus rufus dissimulatus","nameComplete":"Macropus rufus dissimulatus Rothschild, 1905","nameFormatted":"<span class=\"scientific-name rank-species\"><span class=\"name\">Macropus rufus dissimulatus<\u002fspan> <span class=\"author\">Rothschild, 1905<\u002fspan><\u002fspan>","nameGuid":"urn:lsid:biodiversity.org.au:afd.name:450930","taxonomicStatus":"synonym","namePublishedIn":null,"namePublishedInYear":null,"namePublishedInID":null,"nameAuthority":"Australian Faunal Directory","infoSourceURL":"http://:biodiversity.org.au/afd.name/450930","datasetURL":"http://collections.ala.org.au/public/show/dr2699"}],"commonNames":[{"nameString":"Red Kangaroo","status":"common","priority":200,"language":"en-AU","infoSourceName":"Australian Faunal Directory","infoSourceURL":"http://biodiversity.org.au/afd.name/277712","datasetURL":"http://collections.ala.org.au/public/show/dr2699"}],"imageIdentifier":"0cb7bd35-b558-4596-83d1-8ffe54b27f93","conservationStatuses":{"QLD":{"dr":"dr652","status":"Least concern wildlife"}},"extantStatuses":[],"habitats":[],"categories":[],"simpleProperties":[],"images":[],"identifiers":[{"identifier":"urn:lsid:biodiversity.org.au:afd.taxon:aa745ff0-c776-4d0e-851d-369ba0e6f537","nameString":"Previous AFD LSID","status":"replaced","subject":null,"format":"lsid","infoSourceName":"Australian Faunal Directory","infoSourceURL":"http://biodiversity.org.au/afd.taxon/aa745ff0-c776-4d0e-851d-369ba0e6f537","datasetURL":"http://collections.ala.org.au/public/show/dr2699"},{"identifier":"urn:lsid:biodiversity.org.au:afd.taxon:ca350bc9-0381-49ef-9f17-c677d5394fc2","nameString":"Previous AFD LSID","status":"replaced","subject":null,"format":"lsid","infoSourceName":"Australian Faunal Directory","infoSourceURL":"http://biodiversity.org.au/afd.taxon/ca350bc9-0381-49ef-9f17-c677d5394fc2","datasetURL":"http://collections.ala.org.au/public/show/dr2699"},{"identifier":"urn:lsid:biodiversity.org.au:afd.taxon:50f41dca-3000-4e8d-9abe-d6550144d901","nameString":"Previous AFD LSID","status":"replaced","subject":null,"format":"lsid","infoSourceName":"Australian Faunal Directory","infoSourceURL":"http://biodiversity.org.au/afd.taxon/50f41dca-3000-4e8d-9abe-d
