=== AtlasOfLivingAustralia/bie-api-changes/species-vernacular-bulk-lookup.new.schema.json
{
  "type": "array",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "minItems": 1,
  "uniqueItems": true,
  "items": {
    "type": "object",
    "required": [
      "author",
      "classs",
      "commonName",
      "conservationStatus",
      "family",
      "genus",
      "guid",
      "idxType",
      "image",
      "imageMetadataUrl",
      "kingdom",
      "largeImageUrl",
      "name",
      "nameComplete",
      "order",
      "parentGuid",
      "phylum",
      "rank",
      "rankId",
      "score",
      "smallImageUrl",
      "taxonomicStatus",
      "thumbnailUrl"
    ],
    "properties": {
      "acceptedConceptGuid": {},
      "acceptedConceptName": {},
      "author": {
        "type": "string",
        "minLength": 1
      },
      "classs": {
        "type": "string",
        "minLength": 1
      },
      "commonName": {
        "type": "string",
        "minLength": 1
      },
      "conservationStatus": {
        "type": "object",
        "properties": {},
        "required": []
      },
      "family": {
        "type": "string",
        "minLength": 1
      },
      "genus": {
        "type": "string",
        "minLength": 1
      },
      "guid": {
        "type": "string",
        "minLength": 1
      },
      "highlight": {},
      "idxType": {
        "type": "string",
        "minLength": 1
      },
      "image": {
        "type": "string",
        "minLength": 1
      },
      "imageMetadataUrl": {
        "type": "string",
        "minLength": 1
      },
      "imageUrl": {},
      "kingdom": {
        "type": "string",
        "minLength": 1
      },
      "largeImageUrl": {
        "type": "string",
        "minLength": 1
      },
      "linkIdentifier": {},
      "name": {
        "type": "string",
        "minLength": 1
      },
      "nameComplete": {
        "type": "string",
        "minLength": 1
      },
      "order": {
        "type": "string",
        "minLength": 1
      },
      "parentGuid": {
        "type": "string",
        "minLength": 1
      },
      "phylum": {
        "type": "string",
        "minLength": 1
      },
      "rank": {
        "type": "string",
        "minLength": 1
      },
      "rankId": {
        "type": "number"
      },
      "score": {
        "type": "number"
      },
      "smallImageUrl": {
        "type": "string",
        "minLength": 1
      },
      "taxonomicStatus": {
        "type": "string",
        "minLength": 1
      },
      "thumbnailUrl": {
        "type": "string",
        "minLength": 1
      }
    }
  }
}

=== AtlasOfLivingAustralia/bie-api-changes/species-vernacular-bulk-lookup.old.json
[{"acceptedConceptGuid":null,"acceptedConceptName":null,"author":"Meisn.","classs":"Equisetopsida","commonName":"Poker Grevillea","conservationStatus":{},"family":"Proteaceae","genus":"Grevillea","guid":"http://id.biodiversity.org.au/node/apni/2918016","highlight":null,"idxType":"TAXON","image":"60f49ea3-4b48-4893-b8d7-1817d93047a7","imageMetadataUrl":"dc","imageUrl":null,"kingdom":"Plantae","largeImageUrl":"60f49ea3-4b48-4893-b8d7-1817d93047a7","linkIdentifier":null,"name":"Grevillea petrophiloides","nameComplete":"Grevillea petrophiloides Meisn.","order":"Proteales","parentGuid":"http://id.biodiversity.org.au/node/apni/3855393","phylum":"Charophyta","rank":"species","rankId":7000,"score":2.9588866,"smallImageUrl":"60f49ea3-4b48-4893-b8d7-1817d93047a7","taxonomicStatus":"accepted","thumbnailUrl":"60f49ea3-4b48-4893-b8d7-1817d93047a7"}]
